# -*- mode: python; -*-

Import('env')

env.Library(
    target='mutable_bson',
    source=[
        'document.cpp',
        'element.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongol/util/safe_num',
        '$BUILD_DIR/mongol/base',
    ],
)

env.Library(
    target='mutable_bson_test_utils',
    source=[
        'mutable_bson_test_utils.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongol/unittest/unittest',
        'mutable_bson',
    ],
)

env.CppUnitTest(
    target='mutable_bson_test',
    source=[
        'mutable_bson_test.cpp'
    ],
    LIBDEPS=[
        'mutable_bson',
        'mutable_bson_test_utils',
    ],
)

env.CppUnitTest(
    target='mutable_bson_algo_test',
    source=[
        'mutable_bson_algo_test.cpp',
    ],
    LIBDEPS=[
        'mutable_bson',
        'mutable_bson_test_utils',
    ],
)

