# -*- mode: python; -*-

Import('env')

mongolbridge = env.Program(
    target="mongolbridge",
    source=[
        "bridge.cpp",
        "mongolbridge_options.cpp",
        "mongolbridge_options_init.cpp"
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongol/client/clientdriver",
        "$BUILD_DIR/mongol/util/net/network",
        "$BUILD_DIR/mongol/util/ntservice_mock",
        "$BUILD_DIR/mongol/util/options_parser/options_parser_init",
    ],
)

env.Install("#/", mongolbridge)
