# -*- mode: python -*-

Import("env")

env.Library(
    target="test_commands_enabled",
    source=[
        "test_commands_enabled.cpp",
    ]
)

env.Library(
    target='server_status_core',
    source=[
        'server_status_internal.cpp',
        'server_status_metric.cpp',
        ],
    LIBDEPS=[
        '$BUILD_DIR/mongol/util/net/hostname_canonicalization_worker',
        '$BUILD_DIR/mongol/base'
        ]
    )

env.Library(
    target="core",
    source=[
        "authentication_commands.cpp",
        "conn_pool_stats.cpp",
        "conn_pool_sync.cpp",
        "connection_status.cpp",
        "copydb_common.cpp",
        "fail_point_cmd.cpp",
        "find_and_modify_common.cpp",
        "hashcmd.cpp",
        "isself.cpp",
        "mr_common.cpp",
        "rename_collection_common.cpp",
        "server_status.cpp",
        "parameters.cpp",
        "user_management_commands_common.cpp",
        "write_commands/write_commands_common.cpp",
        "generic.cpp",
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongol/client/clientdriver',
        '$BUILD_DIR/mongol/db/audit',
        '$BUILD_DIR/mongol/db/auth/authcommon',
        '$BUILD_DIR/mongol/db/auth/authorization_manager_global',
        '$BUILD_DIR/mongol/db/auth/serverauth',
        '$BUILD_DIR/mongol/db/commands',
        '$BUILD_DIR/mongol/db/commands/test_commands_enabled',
        '$BUILD_DIR/mongol/db/common',
        '$BUILD_DIR/mongol/db/curop',
        '$BUILD_DIR/mongol/db/exec/working_set',
        '$BUILD_DIR/mongol/db/index/key_generator',
        '$BUILD_DIR/mongol/db/index_names',
        '$BUILD_DIR/mongol/db/lasterror',
        '$BUILD_DIR/mongol/db/log_process_details',
        '$BUILD_DIR/mongol/db/matcher/expressions',
        '$BUILD_DIR/mongol/db/matcher/expressions_geo',
        '$BUILD_DIR/mongol/db/matcher/expressions_text',
        '$BUILD_DIR/mongol/db/repl/isself',
        '$BUILD_DIR/mongol/db/repl/repl_coordinator_global',
        '$BUILD_DIR/mongol/db/server_options',
        '$BUILD_DIR/mongol/db/server_parameters',
        '$BUILD_DIR/mongol/db/startup_warnings_common',
        '$BUILD_DIR/mongol/db/stats/counters',
        '$BUILD_DIR/mongol/db/stats/timer_stats',
        '$BUILD_DIR/mongol/logger/parse_log_component_settings',
        '$BUILD_DIR/mongol/s/client/sharding_client',
        '$BUILD_DIR/mongol/s/write_ops/batch_write_types',
        '$BUILD_DIR/mongol/scripting/scripting_common',
        '$BUILD_DIR/mongol/util/cmdline_utils/cmdline_utils',
        '$BUILD_DIR/mongol/util/foundation',
        '$BUILD_DIR/mongol/util/processinfo',
        'server_status_core',
    ],
    LIBDEPS_TAGS=[
        # Depends on mongol::exitCleanly.
        'incomplete',
    ],
)



env.Library(
    target='killcursors_common',
    source=[
        'killcursors_common.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongol/db/audit',
        '$BUILD_DIR/mongol/db/commands',
        '$BUILD_DIR/mongol/db/auth/authorization_manager_global',
        '$BUILD_DIR/mongol/db/query/command_request_response',
    ],
)

env.CppUnitTest(
    target="index_filter_commands_test",
    source=[
        "index_filter_commands_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongol/db/serveronly",
        "$BUILD_DIR/mongol/util/ntservice_mock",
    ],
    NO_CRUTCH = True,
)

env.CppUnitTest(
    target="mr_test",
    source=[
        "mr_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongol/db/serveronly",
        "$BUILD_DIR/mongol/util/ntservice_mock",
    ],
    NO_CRUTCH = True,
)

env.CppUnitTest(
    target="plan_cache_commands_test",
    source=[
        "plan_cache_commands_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongol/db/serveronly",
        "$BUILD_DIR/mongol/util/ntservice_mock",
    ],
    NO_CRUTCH = True,
)
